### ISSUE TITLE
app:transformClassesWithJarMergingForDebug

### ISSUE THREAD

**Issue by zjxuzhj** [hiliving/Ganks#1]
代码拉下来报文件冲突。
查了下是com.squareup.retrofit2:converter-gson:2.1.0  和bomb都依赖的gson
楼主没问题么？

65535也没有处理，楼主那能运行么。。。

**Comment by hiliving** [comment]
我重新拉了下，可以运行，你是用的studio的git么？

**Comment by zjxuzhj** [comment]
是啊。难道这也有坑？

**Comment by hiliving** [comment]
不应该啊，你的studio版本是2.3.3么，gradle版本3.3么

**Comment by zjxuzhj** [comment]
是啊。和你一样的。但是你是没处理依赖冲突和65535吧
bmob 包和 retrofit2 是 冲突的啊

**Comment by zjxuzhj** [comment]
http://blog.csdn.net/a214024475/article/details/73728971
解决方法类似于这个

**Comment by hiliving** [comment]
你自己处理了可以跑了是么，我换了一台电脑，新搭了环境，重新拉了，没问题可以跑，需要注意的是在project structure里，SDKlocation选项，中间的JDK location一定要打勾，选用推荐的那个，不能自己指定jdk目录，否则会报错。

**Comment by zjxuzhj** [comment]
我用的是推荐的那个。应该是环境配置的问题。
